global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: 'fraud-worker'
    static_configs:
      - targets: ['worker:8001']

  - job_name: 'fraud-api'
    static_configs:
      - targets: ['api:8000'] # Add this to monitor the FastAPI app